# Generated by Django 3.2.7 on 2021-11-16 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banker', '0003_auto_20211019_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banker',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
