# Generated by Django 3.2.7 on 2021-09-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AB3_App', '0002_banker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='state',
            field=models.CharField(choices=[('AV', 'Avaiable'), ('DB', 'Doubtful'), ('RO', 'Ruled Out')], default='AV', max_length=100),
        ),
    ]
