# Generated by Django 3.2.7 on 2021-09-27 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AB3_App', '0003_alter_player_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='AB3_App.team'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='assists',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='relation',
            name='rebounds',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='relation',
            name='team_mate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_mates', to='AB3_App.player'),
        ),
    ]
