# Generated by Django 3.2.7 on 2021-09-27 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AB3_App', '0004_auto_20210927_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='team_mate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_mate', to='AB3_App.player'),
        ),
    ]
