# Generated by Django 3.2.7 on 2021-09-27 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AB3_App', '0005_alter_relation_team_mate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation', to='AB3_App.player'),
        ),
    ]
