# Generated by Django 3.2.7 on 2021-09-30 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.FloatField(default=0.0)),
                ('assists', models.FloatField(default=0.0)),
                ('rebounds', models.FloatField(default=0.0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation', to='player.player')),
                ('team_mate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_mate', to='player.player')),
            ],
        ),
    ]
