# Generated by Django 3.2.7 on 2021-10-05 22:41

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='player',
            managers=[
                ('manager_extend', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='state',
            field=models.CharField(choices=[('AV', 'Avaiable'), ('PB', 'Probable'), ('QU', 'Questionable'), ('DB', 'Doubtful'), ('RO', 'Ruled Out')], default='AV', max_length=100),
        ),
    ]
